- name: Setup cart component/node
  hosts: cart
  become: true
  tasks: 
    - name: disable nodejs
      ansible.builtin.command: dnf module disable nodejs -y
    - name: enable nodejs
      ansible.builtin.command: dnf module enable nodejs:20 -y
    - name: isntall nodejs
      ansible.builtin.package:
         name: nodejs
         state: present
    - name: create roboshop system cart
      ansible.builtin.user:
        name: roboshop
        comment: RoboShop System cart
        system: true
        shell: /sbin/nologin
        home: /app
    - name: create app directory
      ansible.builtin.file:
         state: directory
         path: /app
    - name: Download the application code 
      ansible.builtin.get_url:
         url: https://roboshop-artifacts.s3.amazonaws.com/cart-v3.zip
         dest: /tmp/cart.zip
    - name: unzip code
      ansible.builtin.unarchive:
         src: /tmp/cart.zip
         dest: /app
         remote_src: yes
    - name: install npm dependencies
      community.general.npm:
         path: /app
    - name: Setup SystemD cart service
      ansible.builtin.copy:
         src: cart.service
         dest: /etc/systemd/system/cart.service   

    - name: enable & start cart deamon
      ansible.builtin.service:
         name: cart
         enabled: true
         state: started

      


