- name: setup catalogue
  hosts: catalogue
  become: true
  tasks:
    - name: disable nodejs
      ansible.builtin.command: dnf module disable nodejs -y
    - name: enable nodejs20
      ansible.builtin.command: dnf module enable nodejs:20 -y
    - name: install nodejs
      ansible.builtin.package:
         name: nodejs
         state: present
    - name: create roboshop system user
      ansible.builtin.user:
        name: roboshop
        comment: RoboShop System user
        system: true
        shell: /sbin/nologin
        home: /app
    - name: create app directory
      ansible.builtin.file:
         state: directory
         path: /app
    - name: Download the application code 
      ansible.builtin.get_url:
         url: https://roboshop-artifacts.s3.amazonaws.com/catalogue-v3.zip
         dest: /tmp/catalogue.zip
    - name: unzip code
      ansible.builtin.unarchive:
         src: /tmp/catalogue.zip
         dest: /app
         remote_src: yes
    - name: install npm dependencies
      community.general.npm:
         path: /app

    - name: Setup SystemD Catalogue Service
      ansible.builtin.copy:
         src: catalogue.service
         dest: /etc/systemd/system/catalogue.service   

    - name: copy mongo repo
      ansible.builtin.copy:
         src: mongo.repo
         dest: /etc/yum.repos.d/mongo.repo   

    - name: install mongodb client mongosh  
      ansible.builtin.package:
         name: mongodb-mongosh
         state: present

    - name: connnect to mongodb catalogue
      ansible.builtin.command: mongosh mongodb.anilkathoju.space --quiet --eval "db.getMongo().getDBNames().indexOf('catalogue')"
      register: catalogue_output

#    - name: evaluate catalogue database
#      community.mongodb.mongodb_shell:
#        login_host: mongodb.anilkathoju.space
#        eval: db.getMongo().getDBNames().indexOf('catalogue')
#      register: catalogue_output

#    - name: print catalogue output
#      ansible.builtin.debug:
#        msg: "{{ catalogue_output }}"  

    - name: load prodcts to mongodb
      ansible.builtin.shell: mongosh --host mongodb.anilkathoju.space </app/db/master-data.js
      when: catalogue_output.stdout | int == 0

    - name: enable & start 
      ansible.builtin.service:
         name: catalogue
         enabled: true
         state: started
         daemon_reload: true









